### ISSUE TITLE
pkgsrc 2014Q1: php-5.5.10 not working with php-5.5.10-extensions

### ISSUE THREAD

**Issue by anjog** [TritonDataCenter/pkgsrc-legacy#198]
Possible reason: 
php-5.5.10: Thread safety is enabled.
php-5.5.10-extensions: Thread safety is disabled.

In comparison with pkgsrc 2013Q4: 
php-5.5.7: Thread safety is disabled.
php-5.5.7-extensions: Thread safety is disabled too.
=> Everythings working fine with 2013Q4 packages.

**Comment by mjansens** [comment]
Hi,
This seems to hit when using Apache2.4,  going back to Apache2.2, php extensions are loaded without problem.

**Comment by mjansens** [comment]
Hi,
Commandline php5.5.10 also works well, so its only the ap24-php55-5.5.10 PHP apache module that shows the problem.

Michel

**Comment by mamash** [comment]
We're working on the problem and yes, it's only a problem for 2014Q1 and the mod_php SAPI. We should have it fixed this week.

**Comment by mamash** [comment]
This was fixed in 2014Q1 over the weekend. The new ap24_php55-5.5.10nb1 package has thread safety disabled, consistent with the rest of the PHP stack.

This also means that if you need mod_php, you'll need switch the (now default) event MPM to the non-threaded prefork MPM in your httpd.conf. Or - use FPM instead, which is slowly becoming a PHP deployment method of choice these days.

**Comment by mjansens** [comment]
Thanks so much Filip,

Michel

**Comment by anjog** [comment]
Hi Filip, best thanks also for my part.

anjog
