### ISSUE TITLE
unrealircd can't launch on 14.1.x amd64

### ISSUE THREAD

**Issue by rmustacc** [TritonDataCenter/pkgsrc-legacy#226]
It was reported in #smartos that unrealircd refused to launch after an openssl related update. Specifically it had the following message: http://pastebin.com/e9wnhtim.

**Comment by mamash** [comment]
Well, sounds like a problem with configuration. There are no mentions of "https://this.is.private.org/cgiirc.conf" in the source code or the default config files, so not really sure where that's coming from.

**Comment by mamash** [comment]
Nevermind, I realized the vague log probably means that the SSL module failed to load because of the OpenSSL version mismatch, which is why the https resource failed to load.

This is actually user inflicted. The unrealirc binary was of course built against the recent 1.0.1j OpenSSL version and that openssl package is available. All the user needs to do is to 'pkgin upgrade' their system to pick up the new OpenSSL package.
