### ISSUE TITLE
security/password-store missing from Darwin 2015Q3

### ISSUE THREAD

**Issue by alanorth** [TritonDataCenter/pkgsrc-legacy#299]
[security/password-store](https://github.com/joyent/pkgsrc/tree/trunk/security/password-store) exists in the source tree, but there are no binaries for Darwin in 2015Q3.

**Comment by jperkin** [comment]
Not all packages available in pkgsrc build on all platforms, and on OSX there are usually a few thousand that do not build at any one time.

For the 2015Q3 x86_64 build, the results page is [here](http://us-east.manta.joyent.com/pkgsrc/public/reports/Darwin/2015Q3/x86_64/20151001.1822/meta/report.html) and can be used to see why a particular package is unavailable.   In the case of password-store, it was due to its dependency sysutils/tree being broken.

I've fixed the sysutils/tree build [here](http://mail-index.netbsd.org/pkgsrc-changes/2015/11/03/msg131860.html) so this package should be available again in the next branch.

**Comment by alanorth** [comment]
Yeah, I appreciate that this must be a ton of work! I ended up installing password-store from the project's git repository manually, but had to finagle it a bit for some other issues.

When you say  the fixed sysutils/tree will be available in the next branch, do you mean 2015Q4? :)

**Comment by jperkin** [comment]
Yeh 2015Q4.  Build machines are busy working on trunk now so I can't really afford to redo a 2015Q3 build to pick it up there.

**Comment by alanorth** [comment]
Or I could just run trunk, eh? Is there any concept like that for pkgsrc, like rolling release binaries?

**Comment by jperkin** [comment]
Absolutely, but source only for now.  I'm planning to start trunk binary builds, but they likely won't start until after 2015Q4 is done.
