### ISSUE TITLE
Ruby-2.2.3 installation issue on SmartOS zones

### ISSUE THREAD

**Issue by benjamin-bergia** [TritonDataCenter/pkgsrc-legacy#302]
I am using the base-64 image (842e6fa6-6e9b-11e5-8402-1b490459e334) version 15.3.0.
Repository is the 2015Q3. When installing ruby using:

```
pkgin in ruby
```

 I get the following error: 

```
---Nov 09 02:32:38: installing libyaml-0.1.6nb1...
---Nov 09 02:32:38: installing ruby22-base-2.2.3...
---Nov 09 02:32:39: installing ruby-2.2.3...
pkg_add: Package `ruby-2.2.3' conflicts with `pkg_alternatives-[0-9]*', and `pkg_alternatives-1.6' is installed.
pkg_add: 1 package addition failed
---Nov 09 02:46:44: installing ruby-2.2.3...
pkg_add: Package `ruby-2.2.3' conflicts with `pkg_alternatives-[0-9]*', and `pkg_alternatives-1.6' is installed.
pkg_add: 1 package addition failed
---Nov 09 02:48:16: installing ruby-2.2.3...
pkg_add: Package `ruby-2.2.3' conflicts with `pkg_alternatives-[0-9]*', and `pkg_alternatives-1.6' is installed.
pkg_add: 1 package addition failed
---Nov 09 02:49:13: installing ruby-2.2.3...
pkg_add: Package `ruby-2.2.3' conflicts with `pkg_alternatives-[0-9]*', and `pkg_alternatives-1.6' is installed.
pkg_add: 1 package addition failed
```

When specifying the version like in

```
pkgin in ruby22
```

Everything works fine.
Is it a normal behavior of the ruby package or something is broken ?

**Comment by jperkin** [comment]
It's normal behaviour, but is definitely confusing for people who don't know what's going on.

The `ruby` package solely exists to provide the `/opt/local/bin/ruby` symlink, pointing to whichever real ruby package you have chosen (in your case `ruby22-base-2.2.3`).  This would ordinarily be fine, however we use the `pkg_alternatives` framework to provide the `/opt/local/bin` symlinks for ruby, as well as others like python, gcc, etc.

So what you're seeing is a conflict between these two meta-packages over which gets to provide the `/opt/local/bin/ruby` symlink.

What I planned to do previously (and will do now so I don't forget) is mark the `ruby` package as broken, so that we simply don't ship it at all, and avoid this confusion.
