### ISSUE TITLE
sha1 checksum of pkgsrc for SmartOS 64-bit is different from the one on the site

### ISSUE THREAD

**Issue by mamalos** [TritonDataCenter/pkgsrc-legacy#312]
Hi everyone,

As the subject explains, after following the site's instructions on downloading the 64-bit version of pkgsrc for SmartOS, the sha1 checksum produced in my machine differs from the one mentioned in the site. I suppose that this is because somebody hasn't updated the site?

Specifically the following commands show:

<pre>
$ curl -Oks https://pkgsrc.joyent.com/packages/SmartOS/bootstrap/bootstrap-2015Q3-x86_64.tar.gz
$ /bin/digest -a sha1 bootstrap-2015Q3-x86_64.tar.gz
b2bd439b18f0b0d094565572b55de2825213f272
</pre>

whereas the sha1 on the site is: 65372cf50f580fa19a8a6a24464349f0d61b99d6

Just to be on the safe side, I haven't installed it, but in case this is an error, please update the site because it makes somebody wonder if everything is OK.

Thanks all!

**Comment by jperkin** [comment]
I can't reproduce this.

```
$ curl -O https://pkgsrc.joyent.com/packages/SmartOS/bootstrap/bootstrap-2015Q3-x86_64.tar.gz
$ ls -l bootstrap-2015Q3-x86_64.tar.gz
-rw-r--r-- 1 jperkin staff 23537615 Jan  6 09:44 bootstrap-2015Q3-x86_64.tar.gz
$ digest sha1 bootstrap-2015Q3-x86_64.tar.gz
SHA1 (bootstrap-2015Q3-x86_64.tar.gz) = 65372cf50f580fa19a8a6a24464349f0d61b99d6
```

I also tried downloading explicitly from all of the mirrors that make up pkgsrc.joyent.com and they all return the same file.  What IP address does pkgsrc.joyent.com return for you?

I'd suggest double checking that the file size is the same in case your download was truncated, and it's also worth configuring your curl so that you don't need to bypass SSL checks with `-k` and ensure you are definitely downloading from our site.

**Comment by mamalos** [comment]
Hmm, you're right. I downloaded it from another machine outside my VPN and the sha1 is correct. It must be some problem within our VPN or on my SmartOS configuration. Thanks and sorry for the trouble, I should have double-checked the cause of the problem by downloading from a different machine before starting this issue.

Thanks again!
