### ISSUE TITLE
percona xtrabackup packages missing in 2016Q1

### ISSUE THREAD

**Issue by pannon** [TritonDataCenter/pkgsrc-legacy#356]
Seems the `xtrabackup` packages are missing for `percona` in 2016Q1.
I believe these packages provided `innobackupexec` before, which is required for cluster setup and operation.

**Comment by mamash** [comment]
Looks like we've caught ourselves in an unfortunate situation here. pkgsrc 2016Q1 comes with boost 1.60, but XtraBackup 2.4.x (which is MySQL 5.7 based) only supports boost up to 1.59 at this point, which is why XtraBackup packages didn't built properly.

I'll investigate, may have to start building with an embedded boost.

[Explanation here](http://mysqlserverteam.com/building-mysql-5-7/#comment-10940).

**Comment by mamash** [comment]
Fixed and next 2016Q1 rebuild will bring this back.

**Comment by mamash** [comment]
Now available in 2016Q1.
