### ISSUE TITLE
Unknown user/group pbulk

### ISSUE THREAD

**Issue by melloc** [TritonDataCenter/pkgsrc-legacy#365]
While doing an upgrade as documented [here](https://pkgsrc.joyent.com/install-on-illumos/) (which seems to have gone without a hitch as far as I can tell), I noticed the following output in my `/var/db/pkgin/pkg_install-err.log` file:

```
...
---Jul 13 18:07:50: installing p5-IO-Socket-INET6-2.72...
---Jul 13 18:07:51: installing mit-krb5-1.10.7nb5...
chown: unknown user id pbulk
chgrp: unknown group: pbulk
---Jul 13 18:07:52: installing tcp_wrappers-7.6.4...
---Jul 13 18:07:52: installing cyrus-sasl-2.1.26nb4...
...
```

I'm guessing that this shouldn't happen, so I figured I should file a bug.

**Comment by melloc** [comment]
(I just realized that the timestamp is from July 13 last year, so maybe this isn't actually an issue anymore.)

**Comment by mamash** [comment]
It's still a problem, and thanks for opening the ticket, because we have encountered this before, but never fixed it. I'll pursue this now, it's a case where the pbulk build setup leaks into final packages and affects many packages.

Unless you have the pbulk:pbulk pair created, it's just visual spam fortunately, the files/dirs end up owned by root as they should.

**Comment by mamash** [comment]
It's fixed in trunk. I'm not going to rebuild existing packages to remove the warnings, but 2016Q2 will have this gone.

**Comment by melloc** [comment]
Sounds good. Thanks Filip!
