### ISSUE TITLE
ikiwiki missing?

### ISSUE THREAD

**Issue by ghost** [TritonDataCenter/pkgsrc-legacy#372]
The [ikiwiki package](http://pkgsrc.se/www/ikiwiki) seems to be missing in the OS X version of pkgsrc. Output of `pkgin search ikiwiki`:

```
wiliki-0.6.2         WikiWiki clone written in Scheme
py27-moin-1.9.7nb2   MoinMoin, a Python clone of WikiWiki
```

I'm using pkgsrc-2016Q1 (after updating; btw. how would I get pkgin print out the currently used version?) and have still ikiwiki-3.20150614 installed.

I'm on OS X 10.11.4

**Comment by jperkin** [comment]
Thanks for the bug report.  This is currently missing due to this dependency failure:

http://us-east.manta.joyent.com/pkgsrc/public/reports/Darwin/trunk/x86_64/20160528.2236/p5-Text-Markdown-Discount-0.11nb2/build.log

I'll take a look at that today, it should be relatively straight-forward to fix.  As for printing the current branch, there's no way to do that directly from pkgin but you could run something like

```
$ awk -F/ '/^PKG_PATH/ {print $(NF-2)}' /opt/pkg/etc/pkg_install.conf
```

or

```
$ awk -F/ '/^[hf]/ {print $(NF-2)}' /opt/pkg/etc/pkgin/repositories.conf
```

to print it.

**Comment by ghost** [comment]
Thank you for looking into it!

P.S.: Shouldn't it be part of pkgin to show the current brach? Wouldn't that make troubleshooting much easier for you guys, if you would provide a command for displaying the version/branch? This is probably worthy of a separate issue…

**Comment by jperkin** [comment]
It would need some thinking about, as it's possible to use multiple repositories, and that feature is hopefully going to see some enhancements soon as part of a GSOC project.  I'm not sure it would end up any simpler than just extracting it directly from the configuration files, but it's probably worth reporting an issue on the pkgin project page anyway to see if others would find it useful.

As for the OS X packages, they will only be tracking trunk from now on rather than the stable branches, so you can assume it would always report "trunk" :)

**Comment by ghost** [comment]
I opened an issue over at [pkgin](https://github.com/NetBSDfr/pkgin/issues/70).

**Comment by jperkin** [comment]
This is now available

```
$ pkgin se ^ikiwiki
ikiwiki-3.20160509   Flexible static site generator with dynamic features
```
