### ISSUE TITLE
When compiling JDBC_FDW for postgreSQL

### ISSUE THREAD

**Issue by TyrfingMjolnir** [TritonDataCenter/pkgsrc-legacy#377]
There is the following issue:
/opt/local/bin/bsdinstall -c -o pbulk -g pbulk -m 755  jdbc_fdw.so '/opt/local/lib/postgresql/jdbc_fdw.so'
bsdinstall: unknown group pbulk

Full
# PATH=/usr/lib/postgresql/9.5/bin/:$PATH make USE_PGXS=1 install
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -pipe -O2 -I/opt/local/include -I/opt/local/include/ncurses -DLDAP_DEPRECATED -I/usr/include -fPIC -shared -o jdbc_fdw.so jdbc_fdw.o -L/opt/local/lib -L/opt/local/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.4 -Wl,-R/opt/local/gcc47/lib/gcc/x86_64-sun-solaris2.11/4.7.4 -L/opt/local/lib -Wl,-R/opt/local/lib -L/usr/lib/amd64 -Wl,-R/usr/lib/amd64  -Wl,-R'/opt/local/lib'  -ljvm
javac -d /opt/local/lib/postgresql JDBCUtils.java JDBCDriverLoader.java
/bin/sh /opt/local/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/opt/local/lib/postgresql'
/bin/sh /opt/local/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/opt/local/share/postgresql/extension'
/bin/sh /opt/local/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/opt/local/share/postgresql/extension'
/opt/local/bin/bsdinstall -c -o pbulk -g pbulk -m 755  jdbc_fdw.so '/opt/local/lib/postgresql/jdbc_fdw.so'
bsdinstall: unknown group pbulk
/opt/local/lib/postgresql/pgxs/src/makefiles/../../src/Makefile.shlib:501: recipe for target 'install-lib-shared' failed
make: **\* [install-lib-shared] Error 1

I got by this by doing: # groupadd pbulk;useradd pbulk

**Comment by mamash** [comment]
This is related to joyent/pkgsrc#365. In essence, PostgreSQL's configure determines the right tool and invocation to install a shared object, and then uses this command to install itself (which is what happens when we build out a binary PostgreSQL package on our cluster, and it's correct), but also embeds this command in the Makefiles that it ships with itself that serve for other (possibly 3rd party) software installation.

The latter is wrong, because the installation tool and situation might differ significantly between the package build system and the dev/production system where the binary package is installed.

I'm trying to figure out a best way out of this.

**Comment by mamash** [comment]
I committed a workaround for this to pkgsrc trunk today. The 2016Q2 package set will have this fixed.
