### ISSUE TITLE
Missing libxml support for PostgreQL

### ISSUE THREAD

**Issue by dca58** [TritonDataCenter/pkgsrc-legacy#403]
SmartOS PostgreQL packages (e.g. postgresql94-server-9.4.6) are not linked against libxml. 
Is there any reason why those xml/xmlpath extensions are not made available ?

**Comment by mamash** [comment]
None, other than it is bizarre, especially now that I chose not include the deprecated XML extensions in the contrib packages, because I was sure we had the server packages compiled against libxml2.

I swear I remember turning that compile time option on years ago in our config files, but I can't track it anywhere. I'll get this in.

**Comment by dca58** [comment]
Thanks...

**Comment by mamash** [comment]
I've set this option as default in our builds, but that will only take effect starting with 2016Q3. I've just backported the change to the 2015Q4 LTS branch (together with some PostgreSQL updates), so that will show up in a few hours from now.

**Comment by mamash** [comment]
As part of PostgreSQL version updates in the LTS 2015Q4 release that were pushed last night, XML was added.

**Comment by dca58** [comment]
Thank a lot !
