### ISSUE TITLE
Missing package: maxima

### ISSUE THREAD

**Issue by baskerville** [TritonDataCenter/pkgsrc-legacy#435]

**Comment by jperkin** [comment]
For which repository?

**Comment by baskerville** [comment]
Darwin.

**Comment by mamash** [comment]
This one is difficult, because maxima needs clisp. We don't have a clisp package on Darwin because one of its deps (ffcall) comes with assembler objects that won't build on a modern 64-bit Darwin platform. Unfortunately ffcall is pretty much abandoned these days and not even MacPorts or HomeBrew seem to carry a package that will build.

**Comment by mamash** [comment]
Just checked and the problem was overcome meanwhile, and maxima is now available on Darwin.
