### ISSUE TITLE
Darwin x86_64 binaries missing from pkgsrc.joyent.com

### ISSUE THREAD

**Issue by mattwillsher** [TritonDataCenter/pkgsrc-legacy#447]
```
# pkgin up
processing remote summary (https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All)...
pkgin: Could not fetch https://pkgsrc.joyent.com/packages/Darwin/trunk/x86_64/All/pkg_summary.gz
```

Peruse of https://pkgsrc.joyent.com/packages/Darwin/trunk shows no x86_64 dir.

**Comment by jperkin** [comment]
Yeh sorry about this, turns out there is a bug in the upload script which under specific circumstances has resulted in the directory being removed. I am currently re-uploading the packages and they should be available again within the next couple of hours, as well as ensuring the upload script is fixed.

**Comment by jperkin** [comment]
These are now available again on all mirrors.
