### ISSUE TITLE
wip submodule points to non existant commit

### ISSUE THREAD

**Issue by mattwillsher** [TritonDataCenter/pkgsrc-legacy#449]
The wip submodule points to commit that doesn't exist. I'm using salt to checkout the repo and submodules. The output is:

```
              Submodule 'wip' (git://github.com/joyent/pkgsrc-wip.git) registered for path 'wip'
              Cloning into '/data/pkgsrc/joyent'...
              Cloning into '/data/pkgsrc/wip'...
              Fetched in submodule path 'wip', but it did not contain 636c54820a5af3c02dc3210b597b5582fb9d36ef. Direct fetching of that commit failed.
```

is this common with the wip submodule? Can it be pointed to an existing commit?

**Comment by jperkin** [comment]
Which branch is this? It looks like the `.gitmodules` on the `joyent/release/2016Q4` branch is missing the `branch` statements to ensure they are pinned to our wip branch.  I'll add those, which should help, but it's also worth noting that I think (could be wrong) that this only happens when you elect to use shallow clones - at least that's the only time I've seen the same error, as if you do a shallow clone and the latest HEAD or branch commit isn't exactly the one referenced by the branch then it'll fail.

**Comment by mattwillsher** [comment]
It's joyent/osx/trunk 

I'll check how salt does the submodule clone.

**Comment by jperkin** [comment]
Oh ok, then yes that probably makes sense as I did a rebase for wip since my last `joyent/osx/trunk` update. Now that the 2016Q4 bits are done I'll do an OSX update today, sorry about that.

**Comment by mattwillsher** [comment]
That's great, thanks.

**Comment by mamash** [comment]
This was resolved earlier. Unfortunately there was a forced update caused by upstream CVS so you may end up having to reconcile that (e.g. by nuking and checking out joyent/osx/trunk again).
