### ISSUE TITLE
py27-zmq is not present in base-multiarch-lts (16.4.0)

### ISSUE THREAD

**Issue by sjorge** [TritonDataCenter/pkgsrc-legacy#459]
Debugging the saltstack bootstrap failure someone reported, I discovered that py27-zmq does not get build for multiarch. It probably should.

See saltstack/salt-bootstrap#1016

**Comment by mamash** [comment]
You should not probably not be using the multiarch images if you need an extensive Python stack available - many Python modules simply do not build and it's non-trivial to make them build properly. That said, I'll have why py-zmq doesn't build in particular and see if I can fix that.

**Comment by sjorge** [comment]
Yep, I also recommended he used base64(-lts). But it would be nice to have this in multiarch too.

**Comment by mamash** [comment]
I failed to update here before, but py27-zmq is fixed in 2016Q4/multiarch now. The problem was that zeromq wasn't converted to multiarch at all, and then the pyzmq setup script was (needlessly) messing with compiler and linker bitness on SunOS, which was breaking the multiarch build.

I still need to push out the py34 and py35 variants, where PLIST needed a minor fix.

**Comment by sjorge** [comment]
Thanks, I will update the issues over at salt-bootstrap too!
