### ISSUE TITLE
lighttpd fails to start

### ISSUE THREAD

**Issue by jeffpc** [TritonDataCenter/pkgsrc-legacy#46]
1) create a base64 smartmachine
2) pkgin in lighttpd
3) edit /opt/local/etc/lighttpd/\* trivially (e.g., set the server root to something that exists
4) svcadm enable lighttpd

the lighttpd service goes into maintenance mode.  Checking the svc log:

2013-04-14 20:03:28: (plugin.c.209) ld.so.1: lighttpd: fatal: libmapmalloc.so.1: No such file or directory 

LD_PRELOADing libmtalloc.so lets lighttpd start.

**Comment by ghost** [comment]
Is it possible to set LD_DEBUG=all, either in the method environment or on the command line while testing this?  That may help us figure out what's wrong.

**Comment by richlowe** [comment]
This is because this patch: https://github.com/joyent/pkgsrc/blob/trunk/www/lighttpd/patches/patch-src_plugin.c

Is either not correct, or not operative.  libumem has to dlopen libmapmalloc.so RTLD_NOLOAD to determine whether it is safe to use sbrk -- in most cases, that will fail.  However, the use of dlerror() here in lighttpd seems to receive the error information, and thus fails itself.

It is not clear to me whether libumem should be doing anything to clear things up so dlerror() is still sane after it has done its test (it seems, to me, like perhaps it should?).

I suspect the linked patch is actually attempting to fix this very problem, though I think fixing it _that way_ is probably not a good idea.

**Comment by richlowe** [comment]
The patch seems to be trying to fix this very issue indeed -- horribly.

lighttpd seems to be using dlerror to attempt to check whether the preceding dlsym() failed -- why in the world doesn't it just check in the direct fashion, based on the value of `init`?

I'd argue that patch-src_plugin.c should be changed to do just that, also (even though it appears that the problem in the 1.9.1 base64 is that the patch is, also, not present)

**Comment by jperkin** [comment]
Sorry it's taken so long to get to this ticket.  The primary issue here was that 1.9.1 did not include the patch in question.  Images released after the patch was added do not appear to exhibit the same issue, so although it may not be a perfect fix it does seem to at least address the immediate problem.  Therefore I'm going to leave it as-is and close this ticket.  If it becomes a problem in the future we'll open a new one and address the fix accordingly.  Thanks!
