### ISSUE TITLE
'xmlreader' PHP extension has limited functionality when 'dom' extension only modular

### ISSUE THREAD

**Issue by Repkit** [TritonDataCenter/pkgsrc-legacy#477]
It seems that the PHP package is compiled without DOM extension enabled and if you enable it afterwards it doesn't matter. 
The problem seems to be https://github.com/php/php-src/blob/PHP-7.0/ext/xmlreader/php_xmlreader.c 
At line 30 (https://github.com/php/php-src/blob/PHP-7.0/ext/xmlreader/php_xmlreader.c#L30) it's verify for DOM support and loading stuff. At line 1121 (https://github.com/php/php-src/blob/PHP-7.0/ext/xmlreader/php_xmlreader.c#L1121) the method "expand" raise an error if HAVE_DOM doesn't exists (it's not included) -  php_error(E_WARNING, "DOM support is not enabled"); . From my understanding HAVE_DOM is set only when the pacakge is compiled with DOM (https://github.com/php/php-src/blob/6053987bc27e8dede37f437193a5cad448f99bce/ext/dom/config.m4) If the extension is added/enabled after it doesn't count...

**Comment by mamash** [comment]
Ignore my previous response, I had another look and it wasn't clear at all from your report that the problem seems to be that the xmlreader compiles differently (namely XMLReader::expand is lost) if the dom extension is not configured too at the same time.

I don't see a good way around this at this point, the checks for dom defeat the whole purpose of being able to build a modular PHP stack.

**Comment by mamash** [comment]
I plan to change pkgsrc to build the dom extension embedded, as there's no extra dependency cost (libxml is already being consumed, anyway). pkgsrc is in 2017Q1 freeze right now, so I'll make this change in a week or so.

**Comment by mamash** [comment]
I made the changes necessary in pkgsrc trunk today: the 'dom' extension now builds into the PHP binary, rather than as a standalone extension. I couldn't find any other check where one extension would require another one (that was not there in some way already).

The commits involved make this a non-trivial change, we won't be bringing it back into existing pkgsrc releases, so 2017Q2 will be the first to have it (end of Q2).

For the record, fixing this the other way around (making both dom and xmlreader separate) worked too, but it was more difficult at the end and didn't feel worth it.
