### ISSUE TITLE
cyrus-sasl-2.1.26nb2: Does not install libsasl2.so.3

### ISSUE THREAD

**Issue by mnaser** [TritonDataCenter/pkgsrc-legacy#68]
When installing Git, cyrus-sasl-2.1.26nb2 is installed as a prerequisite because it is supposed to provide libsasl2.so.3

The cyrus-sasl-2.1.26nb2 package does not seem to install libsasl2.so.3 into the system which breaks git with HTTPS.  Other packages such as Python's psycopg2 fail to connect as well.  This issue can be created on a fresh host (GZ):

```
$ curl -s http://pkgsrc.joyent.com/packages/SmartOS/bootstrap/bootstrap-2013Q2-x86_64.tar.gz | gzcat | (cd /; sudo tar -xpf -)
$ pkgin -y update
$ pkgin -y in scmgit-base
$ git clone https://github.com/joyent/pkgsrc.git
```

I don't have the error anymore because I compiled the library again from source and it seems to have resolved it, but it was along the following lines for psycopg2:

```
ld.so.1: python2.7: fatal: libsasl2.so.3: open failed: No such file or directory
```

According to build logs, it seems that the library is being built, just not packaged/shipped out for some reason.

**Comment by mamash** [comment]
Each of the packages mentioned is fine, and cyrus-sasl-2.1.26nb2 actually does install /opt/local/lib/libsasl2.so.3. However, since you're effectively changing package repository, you must destroy the previous pkgin database (rm /var/db/pkgin/pkgin.db), otherwise you'll end up with completely faux dependencies and/or get packages missing. It's a known bug (sadly one of many) in pkgin that it won't clear everything properly on a 'pkgin update'.

You can tell that without zapping the database, you'll see crazy things being installed, as you 'pkgin in scmgit-base' in your example (I'm talking about things like python27 _and_ python33 _and_ mysql-client), whereas with a clean database, the list of packages installed as dependencies is modest and sane.

**Comment by jperkin** [comment]
The issue here is actually that you're trying to install in the GZ.  The packages you are seeing issues with are ones which require that users be installed, which is not supported in the GZ.  What happens in that case is that the package install is left in a limbo state - the pkg tools think that the package is installed, but none of the files are on disk.

We need to fix the pkg tools so that they clean up properly when the install script fails, but the short summary is that you can't do this in the GZ.

As a workaround, you could download the failing packages (any which need to create users) and unpack the .tgz manually to `/opt/local`.  However, given the lack of user, it cannot be guaranteed that they will actually work, though in your case at least sasl should be ok as you only need the library.

**Comment by mamash** [comment]
Ah, I missed the part of GZ. Thanks, Jonathan.

**Comment by jperkin** [comment]
I've fixed the pkg_add bug, the fix will be available in pkgsrc-2013Q3.

http://mail-index.netbsd.org/pkgsrc-changes/2013/08/21/msg093757.html
