### ISSUE TITLE
man doesn't work in base-1.8.1.

### ISSUE THREAD

**Issue by ilc** [TritonDataCenter/pkgsrc-legacy#7]
It reports:

Reformatting page.  Please Wait...nroff: Cannot find library -mandoc

**Comment by rmustacc** [comment]
man by default is an alias in one of the bash rc scripts. You can work around this by getting rid of it.

**Comment by mamash** [comment]
Yeah, you really need groff to parse the pkgsrc (BSD) man pages. There's an alias in .profile that adds the needed helpful args to man so that it can do the job, but it assumes you have the groff package installed.

-F
1. 10. 2012 v 16:39, Robert Mustacchi notifications@github.com:

**Comment by rmustacc** [comment]
@mamash In this case though it seems to be being told to look for mandoc macros. Does groff actually supply those?

**Comment by mamash** [comment]
Cannot reproduce. To sum up, the platform (SmartOS) 'man' cannot parse the pkgsrc (BSD) man pages. It needs groff from pkgsrc - which is why the 'base' images come with groff preinstalled, and 'man' is aliased to add the needed args.

I don't have base 1.8.1 at hand right now, but this works out of the box on base 1.9.x and 13.1.x. The alias is also present in the /etc/skel files, so make sure to 'useradd -m' to create the default profile files if you add a new user.
