### ISSUE TITLE
mismatch in available packages between 'pkgin avail' and packages in the http-browsable repo

### ISSUE THREAD

**Issue by bixu** [TritonDataCenter/pkgsrc-legacy#73]
We're noticing some discrepancies between the 13.1 pkgsrc repository index through http and pkgin... something like 300 packages are missing from pkgin (even after a `pkgin update -f -y`). Anyone have any ideas as to why that might be?

We're specifically trying to get access to the phantomjs package, and it's showing up in the http index but not the pkgin repository.

@hjhart

**Comment by mamash** [comment]
There's something odd going on with the pkgin available right now in 2013Q1. Something to do with how pkgin updates its database rather. Can't reproduce the problem in 2013Q2. We'll have a look.

**Comment by mamash** [comment]
On a pristin base-13.1.0 (2013Q1) VM, I couldn't really reproduce any of the problem (originally I tried on an old existing zone, where pkgin db is likely messed up due to other things). The 300-something difference can be attributed to the fact that previous versions of packages are left in place (on the HTTP server), but do not show up in the pkgin database. This is so that pkgin with a stale database doesn't give you a weird "this package doesn't exist" kind of error, or to fetch manually via 'pkg_add'.

On a clean base-13.1.0 zone, the current package count is 2353 (as per 'pkgin av|wc -l') and a search does find phantomjs-1.9.1 (in the 32bit package set - phantomjs doesn't currently build 64bit, so won't show up on a base64-13.1.0 VM).

You can confirm by cat'ing the pkg_summary file (which pkgin imports for its database):

```
curl http://pkgsrc.joyent.com/packages/SmartOS/2013Q1/i386/All/pkg_summary.bz2 | gzcat
```

If you grep that for ^PKGNAME, that should match what 'pkgin av' shows. If the two do not match, odds are the pkgin database is corrupt and won't fix with a mere 'pkgin up'. You can destroy /var/db/pkgin/pkgin.db (or move it aside), then try 'pkgin -y up' and see if it makes any difference.

**Comment by hjhart** [comment]
The problem could've been that we were running the command on a 64bit machine – @bixu can you confirm that?

**Comment by mamash** [comment]
OK. The problem that you _might_ be facing is that there's no phantomjs-1.9.x package in the x86_64 set, because PhantomJS doesn't support a 64bit build on SunOS (yet). There's a long standing bug ticket on that upstream:

https://github.com/ariya/phantomjs/issues/10521

The reason why not even phantomjs-1.4.1 (which is there in the http dirlisting) is showing up in pkgin, is because the pbulk building system considers phantomjs a failure on x86_64 (because the current version fails to build in 64bit), and it doesn't know about the left over older versions - and it won't include it when processing pkg_summary that pkgin ultimately bases on.

**Comment by hjhart** [comment]
I discovered the issue with this in a later task where I was dealing with pkgin. The problem was that the pkg_summary.gz file had inconsistent data than what was showing up in the HTTP repository index. Thereby, the database that updated during `pkgin up` was consistent only with the pkg_summary.gz, not with the repo itself.

(This is just a FYI, and no action needs to be taken from it)
